### ISSUE TITLE
ImportError: No module named socks

### ISSUE THREAD

**Issue by TurboProgramming** [Ethical-H4CK3R/Instagram#23]
```
e210:Instagram ardacebi$ python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 15, in <module>
    from Core.tor import TorManager
  File "/Users/ardacebi/Instagram/Core/tor.py", line 3, in <module>
    import socks
ImportError: No module named sock
```

Why is this happening?

**Comment by TurboProgramming** [comment]
issue resolved
