### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostD1** [Ethical-H4CK3R/Instagram#3]
Hi I have a problem with this

Traceback (most recent call last):
  File "Instagram.py", line 155, in <module>
    BruteForce(Email,passwrd)
  File "Instagram.py", line 42, in BruteForce
    if Br.geturl() != Url:
  File "/usr/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 334, in geturl
    raise BrowserStateError("not viewing any document")
mechanize._mechanize.BrowserStateError: not viewing any document

Can you help me please?
Thanks

**Comment by Nicolas06200** [comment]
Same for me, help please
